# Generated by Django 4.1.4 on 2023-01-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_cat_posts', to='blogs.categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labeltag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_post_tags', to='blogs.labeltag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='metatag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
