# Generated by Django 4.1.4 on 2023-01-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'codes'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('codename', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_codes_comm', to='blogs.codes')),
                ('postname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_post_comm', to='blogs.post')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
