# Generated by Django 4.1.4 on 2023-01-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_alter_post_author_alter_post_labeltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_cat_codes', to='blogs.categories'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='labeltag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_code_tags', to='blogs.labeltag'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='metatag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
