# Generated by Django 4.1.4 on 2023-01-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_codes_author_alter_codes_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bannerimage',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/'),
        ),
    ]
