# Generated by Django 4.1.4 on 2023-01-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='codename',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_codes_comm', to='blogs.codes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_post_comm', to='blogs.post'),
        ),
    ]
